import Homepage from '@/components/Homepage'
import Head from 'next/head'

const API_KEY = process.env.API_KEY

export default function Home({results}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Homepage results={results}/>
    </>
  )
}


export async function getStaticProps(){
  const res = await fetch(`https://api.rawg.io/api/games?key=${API_KEY}&page_size=20`)
  const data = await res.json()
  const results = data.results

  return{
    props: {
      results
    }
  }
}


